export const PRODUCT_REQ = "PRODUCT_REQ"
export const PRODUCT_FAILURE = "PRODUCT_FAILURE"

// Post
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"

// GET
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS"

// Patch
export const PATCH_PRODUCT_SUCCESS = "PATCH_PRODUCT_SUCCESS"